# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TouchBase' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  
  use_frameworks!
    
	pod 'KGFloatingDrawer', '~> 0.2.0'
	pod 'DropDown'

	pod 'M13Checkbox'
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'JDropDownAlert'
	pod 'ObjectMapper', '~> 1.3'
	pod 'HanekeSwift'
	pod 'SwiftOverlays', '~> 2.0.0'
	pod 'Refresher'
	pod 'DLRadioButton', '~> 1.4'
	pod 'DatePickerDialog'	
	pod 'ZMSwiftRangeSlider', '~> 0.1.3'
    
    pod 'Fusuma'
    pod 'TwitterKit'
    pod 'TwitterCore'
    pod 'Fabric'
    pod 'Crashlytics'
    
    pod 'Mixpanel-swift', '1.0.1'
  # Pods for TouchBase

end
